package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_item
 *
 * @mbg.generated do_not_delete_during_merge Mon Jul 29 17:12:30 CST 2019
 */
public class TbItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item.id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item.item_name
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private String itemName;

    /**
     * Database Column Remarks:
     *   商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item.item_price
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private Float itemPrice;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item.item_detail
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private String itemDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_item.id
     *
     * @return the value of tb_item.id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_item.id
     *
     * @param id the value for tb_item.id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_item.item_name
     *
     * @return the value of tb_item.item_name
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_item.item_name
     *
     * @param itemName the value for tb_item.item_name
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_item.item_price
     *
     * @return the value of tb_item.item_price
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public Float getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_item.item_price
     *
     * @param itemPrice the value for tb_item.item_price
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setItemPrice(Float itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_item.item_detail
     *
     * @return the value of tb_item.item_detail
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public String getItemDetail() {
        return itemDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_item.item_detail
     *
     * @param itemDetail the value for tb_item.item_detail
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setItemDetail(String itemDetail) {
        this.itemDetail = itemDetail == null ? null : itemDetail.trim();
    }
}