package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_orderdetail
 *
 * @mbg.generated do_not_delete_during_merge Mon Jul 29 17:12:30 CST 2019
 */
public class TbOrderdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.order_id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.item_id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private Integer itemId;

    /**
     * Database Column Remarks:
     *   商品总价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.total_price
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private Double totalPrice;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.status
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderdetail.id
     *
     * @return the value of tb_orderdetail.id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderdetail.id
     *
     * @param id the value for tb_orderdetail.id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderdetail.order_id
     *
     * @return the value of tb_orderdetail.order_id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderdetail.order_id
     *
     * @param orderId the value for tb_orderdetail.order_id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderdetail.item_id
     *
     * @return the value of tb_orderdetail.item_id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderdetail.item_id
     *
     * @param itemId the value for tb_orderdetail.item_id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderdetail.total_price
     *
     * @return the value of tb_orderdetail.total_price
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderdetail.total_price
     *
     * @param totalPrice the value for tb_orderdetail.total_price
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderdetail.status
     *
     * @return the value of tb_orderdetail.status
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderdetail.status
     *
     * @param status the value for tb_orderdetail.status
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}