package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_order
 *
 * @mbg.generated do_not_delete_during_merge Mon Jul 29 17:12:30 CST 2019
 */
public class TbOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.user_id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_number
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    private String orderNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.id
     *
     * @return the value of tb_order.id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.id
     *
     * @param id the value for tb_order.id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.user_id
     *
     * @return the value of tb_order.user_id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.user_id
     *
     * @param userId the value for tb_order.user_id
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_number
     *
     * @return the value of tb_order.order_number
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_number
     *
     * @param orderNumber the value for tb_order.order_number
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }
}