package test.dao;

import java.util.List;
import test.model.SysRolePrivilege;

public interface SysRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    int insert(SysRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    List<SysRolePrivilege> selectAll();
}