package test.dao;

import java.util.List;
import test.model.TbOrder;

public interface TbOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    int insert(TbOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    TbOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    List<TbOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    int updateByPrimaryKey(TbOrder record);
}