package test.dao;

import java.util.List;
import test.model.TbOrderdetail;

public interface TbOrderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    int insert(TbOrderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    TbOrderdetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    List<TbOrderdetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbg.generated Mon Jul 29 17:12:30 CST 2019
     */
    int updateByPrimaryKey(TbOrderdetail record);
}